#!/bin/bash
if [[ ! -f sseutils64.nasm ]]; then cp ../../sseutils64.nasm .; fi;
nasm -f elf64 sseutils64.nasm;
for f in $(ls *64.nasm); do
	nasm -f elf64 $f;
done;
gcc -m64 -msse -mavx -O0 -no-pie *64.o pst64c.c -o pst64 -lm
