#!/bin/bash
if [[ ! -f sseutils32.nasm ]]; then cp ../../sseutils32.nasm .; fi;
nasm -f elf32 sseutils32.nasm;
for f in $(ls *32.nasm); do
	nasm -g -f elf32 $f;
done;
gcc -g -m32 -msse -O0 -no-pie *32.o pst32c.c -o pst32 -lm
for arg; do pars=$pars" "$arg;done;
./pst32 $pars
