#!/bin/bash
if [[ ! -f sseutils64.nasm ]]; then cp ../../sseutils64.nasm .; fi;
nasm -f elf64 sseutils64.nasm;
for f in $(ls *64.nasm); do
	nasm -g -f elf64 $f;
done;
gcc -g -m64 -msse -O0 -no-pie *64.o pst64c.c -o pst64 -lm
for arg; do pars=$pars" "$arg;done;
./pst32 $pars
